- name: Using cli_command agnostic modules                                                                         
  hosts: arista_switches                                                                                           
  gather_facts: false                                                                                              
  connection: network_cli                                                                                          
  become: yes                                                                                                      
  become_method: enable                                                                                            
                                                                                                                   
  vars:
    ansible_ssh_pass: alta3

  tasks:
    - name: run multiple commands on remote nodes
      ansible.netcommon.cli_command:
        command: "{{ item }}"
      loop:
        - show version
        - show interfaces
      register: results 

    - name: Extract and show the switch IP address
      debug:
        msg: "{{ results.results[1].stdout | regex_search('(?:\\d+\\.\\d+\\.\\d+\\.\\d+)') }}"

